// The portfolio's vocabulary and the INDEX.md table: statuses, themes, the store paths, the
// validators, the sort, and the render and parse of the index. No disk and no git, so every other
// file here can import it. Split out of projects.mjs (#37), code unchanged.

export const STATUSES = {
  active: '🟢 active',
  ops: '🔵 ops',
  paused: '🟡 paused',
  done: '✅ done',
};
export const STATUS_ORDER = ['active', 'ops', 'paused', 'done'];
// Themes partition the index into readable sections. Six members chosen against the real
// 39 rows, not invented: fewer and citsim's worldbuilding rows sit somewhere that does not
// describe them, more and a section holds one project.
// Adding or renaming one? Markdown cannot interpolate this, so six prose statements go stale with
// it: SKILL.md:18-19 and :30, and README.md's themes paragraph under "What it is", plus the count
// word in each ("Six themes", "one of six themes"). The CLI's own copies are derived (HELP and validateTheme both interpolate
// THEME_ORDER) and need no edit. The inventory lives here so the edit and its fallout are adjacent.
export const THEMES = {
  work: 'Work',
  'job-search': 'Job search',
  tooling: 'Tooling',
  homelab: 'Homelab',
  worldbuilding: 'Worldbuilding',
  personal: 'Personal',
};
// Derived, never a second list: a hand-maintained order drifts from the enum the first time
// a theme is added and the drift is silent.
export const THEME_ORDER = Object.keys(THEMES);
// The section a row with no theme lands in. Not a seventh theme: nothing can be SET to it,
// and with every row themed the section renders on no row and never appears.
export const UNTHEMED = 'Unthemed';
export const PROJECTS_DIR = 'docs/projects';
// The sharded store, one file per project, and the only store there is.
export const REL_ENTRIES = `${PROJECTS_DIR}/entries`;
// The packed file REL_ENTRIES replaced. DELETED from the worktree in 1.3.0, along with the
// self-migration and the fallback that read it, and kept as a constant for one reason: git
// HISTORY. `projects log` names it in its pathspec so the log does not cut off at the migration,
// and projects-index-guard.mjs still refuses a hand-edit to it, because writing a file no verb
// reads is silently ignored, which is worse than being refused. Nothing reads it from disk.
export const REL_STORE = `${PROJECTS_DIR}/_projects.json`;
export const REL_INDEX = `${PROJECTS_DIR}/INDEX.md`;
// A slug is a FILENAME now (docs/projects/entries/<slug>.json), so this has to be at least as
// strict as the store layer's own check. Tightened to require an alphanumeric first character:
// a leading '-' reads as a flag to git and to argv parsing, and a leading '_' could name the
// `_meta.json`-shaped file the record reader would read straight back as a project. Refused
// here rather than inside writeStore because cmdRegister writes the page skeleton before it
// saves the row, and its no-orphan-page guarantee only holds while nothing after that write
// can still refuse. Every one of the 60 live slugs passes.
const SLUG_RE = /^[A-Za-z0-9][A-Za-z0-9_-]*$/;

export function validateStatus(s) {
  if (!Object.prototype.hasOwnProperty.call(STATUSES, s)) {
    throw new Error(`unknown status "${s}", expected one of ${STATUS_ORDER.join(', ')}`);
  }
  return s;
}

// No `projects: ` prefix, matching validateStatus and validateSlug. DELIBERATE below keys
// off that, and main maps this message to exit 2: a bad theme is bad input, not a bug here.
export function validateTheme(t) {
  if (!Object.prototype.hasOwnProperty.call(THEMES, t)) {
    throw new Error(`unknown theme "${t}", expected one of ${THEME_ORDER.join(', ')}`);
  }
  return t;
}

export function validateSlug(s) {
  if (typeof s !== 'string' || !SLUG_RE.test(s)) throw new Error(`invalid slug "${s}"`);
  return s;
}

// A record file is hand-editable, so every field here tolerates junk: an unrecognised
// status ranks last rather than -1 (which would sort a typo AHEAD of active), and a
// missing lastTouched/slug sorts last rather than throwing on undefined.localeCompare.
const rank = (s) => (STATUS_ORDER.includes(s) ? STATUS_ORDER.indexOf(s) : STATUS_ORDER.length);

export function sortProjects(list) {
  return [...list].sort((a, b) =>
    rank(a.status) - rank(b.status) ||
    (b.lastTouched || '').localeCompare(a.lastTouched || '') ||
    (a.slug || '').localeCompare(b.slug || ''));
}

const INDEX_HEADER = `# Projects: Portfolio Index

*Generated by the \`projects\` CLI from \`entries/<slug>.json\`.
Do not hand-edit this file.*

One row per active effort. Each project links to its narrative
page in this folder, which is where its \`## Current state\` lives.
This table carries pointers only.

Change a row with \`projects status <slug> <status>\`, or its other
fields with \`projects set <slug> --where W --repo R\`. Rename one with
\`projects rename <old> <new>\`. Change what a project is *doing* with
\`projects current <slug>\`, which writes to its page.
A hand-edit here is overwritten on the next render.
`;

const INDEX_COLUMNS = '| Project | Status | Where | Last touched |';

// A pipe splits the cell and shifts every column after it. A newline does worse, it ends the
// row early and the tail becomes a phantom project on parse. Refuse both loudly rather than
// write a corrupt table. Covers `page` too: it lands inside the link target. And `theme`, which
// is interpolated into a `## ` section heading, so a line break there forges a whole section plus
// the phantom row under it. Write paths refuse an unrenderable value here, read paths squash it
// (renderList): a read must never fail on a bad row it only displays.
const UNRENDERABLE = /[|\r\n]/;
export function assertRenderable(p) {
  const fields = [p.name, ...(p.where || []), p.lastTouched || '', p.page || '', p.theme || ''];
  for (const f of fields) {
    if (UNRENDERABLE.test(String(f))) {
      throw new Error(`projects: pipe or line break in a rendered field ("${f}")`);
    }
  }
  return p;
}

// The label a section is titled with. A known theme gets its display name. An unrecognised
// one gets its own raw value, so a typo names itself in the index instead of being absorbed
// into a real section. A row with none gets UNTHEMED.
export function themeLabel(theme) {
  if (!theme) return UNTHEMED;
  return THEMES[theme] ?? theme;
}

// Insertion-ordered: every enum label first so an empty theme still holds its position, then
// any unrecognised label as encountered, then UNTHEMED last however it got in. Empty sections
// are dropped by the caller, not here, so renderList and renderIndex agree on the order.
export function groupByTheme(rows) {
  const sections = new Map(THEME_ORDER.map((t) => [THEMES[t], []]));
  for (const p of rows) {
    const label = themeLabel(p.theme);
    if (!sections.has(label)) sections.set(label, []);
    sections.get(label).push(p);
  }
  if (sections.has(UNTHEMED)) {
    const last = sections.get(UNTHEMED);
    sections.delete(UNTHEMED);
    sections.set(UNTHEMED, last);
  }
  return sections;
}

// Extracted from the map below so renderIndex reads as grouping rather than as row building.
// The try/catch stays here, at the one place that has the slug, for the reason below.
function renderRow(p) {
  // Both throws name the offending value and neither knows which row it came from, and one
  // bad row refuses every mutating verb, including a verb touching only healthy rows. So the
  // slug is added here.
  try {
    assertRenderable(p);
    const label = p.page ? `[${p.name}](${p.page})` : p.name;
    // `|| ''` on the date: Task 1 tolerates a missing lastTouched, and without this the cell
    // renders the literal string "undefined" and round-trips into the store as that string.
    return `| ${label} | ${STATUSES[validateStatus(p.status)]} | ${(p.where || []).join(' · ')} | ${p.lastTouched || ''} |`;
  } catch (e) {
    throw new Error(`${(e && e.message) || e} on project "${p.slug}"`);
  }
}

// One section per non-empty theme. Sorting is unchanged and applies WITHIN a section, so a
// row's neighbours change but its rank against them does not.
export function renderIndex(store) {
  const parts = [INDEX_HEADER];
  for (const [label, rows] of groupByTheme(sortProjects(store.projects))) {
    if (!rows.length) continue;
    parts.push(`## ${label}`, '', INDEX_COLUMNS, '|---|---|---|---|', ...rows.map(renderRow), '');
  }
  // The join leaves exactly one trailing newline because every section ends with ''. The
  // replace is belt and braces for a store with no projects at all, where parts is just the
  // header and the file must still end in a single newline.
  return parts.join('\n').replace(/\n*$/, '\n');
}

const RENDERED_TO_WORD = Object.fromEntries(
  Object.entries(STATUSES).map(([word, rendered]) => [rendered, word]));

const RENDERED_TO_THEME = Object.fromEntries(
  Object.entries(THEMES).map(([key, label]) => [label, key]));

// The inverse of renderIndex, for the one-off migration of the hand-typed INDEX.md and for
// the round-trip test. The slug is DERIVED here. The store's own slug stays authoritative.
export function parseIndex(text) {
  const projects = [];
  let theme;
  for (const line of text.split('\n')) {
    // Theme is the first store field that decides WHERE a row renders, so parseIndex has to
    // recover it or the byte-stable round trip breaks and every row re-renders as Unthemed.
    // Three cases, one expression, and it is a true inverse of themeLabel: a known label maps
    // back to its key, UNTHEMED maps back to no theme, and an unrecognised heading maps back
    // to itself so a typo section survives a round trip instead of being relabelled.
    const heading = line.match(/^## (.+)$/);
    if (heading) {
      const label = heading[1].trim();
      theme = RENDERED_TO_THEME[label] ?? (label === UNTHEMED ? undefined : label);
      continue;
    }
    if (!line.startsWith('| ')) continue;
    const c = line.split('|').map((s) => s.trim());
    if (c.at(-1) === '') c.pop(); // trailing pipe
    // c[0] is '' (leading pipe): name, status, where, ..., lastTouched
    // A short row would alias label and c.at(-1) to the same cell and parse a project with
    // status undefined. An all-dashes row is the separator in its spaced `| --- | --- |` form,
    // which would otherwise parse as a project named "---". One guard each, same loop.
    if (c.length < 5 || c.slice(1).every((cell) => /^:?-+:?$/.test(cell))) continue;
    const [, label, status, where] = c;
    // Skip the header ROW, not every row that merely STARTS with "Project": a pageless project
    // named "Project Atlas" renders as `| Project Atlas | 🟢 active | … |` and a startsWith
    // test dropped it silently. Both header shapes, the 4-column rendered one and the legacy
    // 5-column hand-typed one, carry the literal cells Project/Status, which no data row can:
    // a rendered status always carries its emoji.
    if (label === 'Project' && status === 'Status') continue;
    // The date comes from the LAST cell, not position 4: the hand-typed table this replaces
    // had a 5th `Next` column BEFORE Last touched (verified, all 21 rows), so reading
    // position 4 would migrate the Next prose in as lastTouched and drop the date.
    const lastTouched = c.at(-1);
    const link = label.match(/^\[(.+)\]\((.+)\)$/);
    projects.push({
      slug: (link ? link[2].replace(/\.md$/, '') : label).toLowerCase().replace(/[^a-z0-9_-]+/g, '-'),
      name: link ? link[1] : label,
      status: RENDERED_TO_WORD[status] ?? status,
      ...(theme ? { theme } : {}),
      where: where ? where.split(' · ') : [],
      page: link ? link[2] : null,
      lastTouched,
    });
  }
  return { version: 1, projects };
}
