#!/usr/bin/env node
// Compress a mailbox window into tags, so code can query what only prose held.
//
// This is the second shape in docs/runbooks/system-one-models.md: many semi-structured fields
// reduced to a few typed columns. An email's subject and snippet carry meaning no column holds, so
// nothing downstream can filter on it. Eight nouls turn each message into eight numbers that sort,
// group and go in a WHERE clause.
//
// ⚠ THIS SENDS EMAIL CONTENT TO A THIRD PARTY (OpenRouter, then TypeSafe). Sender, subject and
// snippet leave the machine. That is fine for Nathan's own job-hunt mailbox and was his explicit
// call on 2026-09-22. It is NOT fine for anything with work or customer data in it, per AGENTS.md:
// customer PII never leaves the machine. There is no allowlist enforcing that here, deliberately —
// a guard that silently decides which mailbox is safe would be worse than a comment you have to
// read. Check what you are piping in.
//
// Usage:
//   python .claude/skills/postman/inbox.py <identity> --days 30 --json | node jevmail.mjs
//   node jevmail.mjs --in window.json --json tags.json
//   node jevmail.mjs --selftest
//
// Deliberately NOT a generic engine. One chunker that knows what an email is, questions written
// out below. The generic version was specced (docs/superpowers/specs/2026-09-22-jevchecker-design.md)
// and dropped until a second real sweep exists to extract it from: every chunker strategy in that
// spec was a guess, and guessing structure before measuring is exactly what went wrong with the
// Orion coefficients the same day.

import fs from 'node:fs';
import assert from 'node:assert';
import { askJev, runPool, toText, noulsFrom, firedTags } from './lib.mjs';

const CONCURRENCY = 6;

// The tag vocabulary. Adding one is nearly free (12 questions cost the same as 1, measured), so the
// bar for including a tag is whether anything would ever filter on it, not what it costs.
//
// ⚠ A tag nobody writes here stays invisible. Jev answers what it is asked and generates no text,
// so it cannot discover that a category was missing. When a sweep keeps surfacing something these
// eight do not name, add a ninth rather than reading around it.
const TAGS = {
  is_rejection: 'This message tells the applicant they were not selected',
  is_interview_invite: 'This message invites the applicant to an interview or a call',
  is_assessment: 'This message asks the applicant to complete a test, take-home or assessment',
  is_recruiter_outreach: 'This is a recruiter approaching the applicant about a role, unprompted',
  is_from_agency: 'The sender is a recruitment agency or staffing firm rather than the hiring employer',
  // ⚠ BOTH OF THESE WERE REWORDED 2026-09-22 after the first live sweep, and the originals are the
  // worked example of how a tag goes wrong. 391 messages, 30-day jobhunt window:
  //
  //   is_automated: 'an automated or no-reply message rather than one a person wrote'  → fired 97%
  //   needs_reply:  'asks the applicant a question or requests an action from them'    → fired 92%
  //
  // Neither answer was wrong. A job-hunt mailbox really is 97% automated, and a LinkedIn alert
  // really does request an action ("apply to these"). They were USELESS, which is a different
  // failure: a tag that fires on almost everything cannot filter anything, and 352 messages came
  // back tagged both automated and needing a reply, which is a contradiction no downstream query
  // can act on.
  //
  // The fix in both cases is to make the RARE case the firing case, and to name the concrete
  // situation rather than the abstract property. Check a new tag's fire rate before trusting it:
  // above ~85% or below ~0.5% it is carrying no information whatever its precision looks like.
  is_personally_written: 'A person wrote this message specifically to this applicant, rather than it being generated by a system or sent to a list',
  needs_reply: 'A person is waiting for the applicant to write back to this particular message',
  mentions_compensation: 'This message states a salary, rate or compensation figure',
  // ADDED 2026-09-22, after the 40%-untagged warning below fired at 80% on the first clean sweep
  // and turned out to be right rather than a false alarm. 274 of the 313 untagged messages were
  // LinkedIn job alerts: a real category the vocabulary simply did not name. This is the failure
  // mode worth remembering — Jev cannot tell you a tag is missing, it can only fail to fire, so
  // the untagged pile is the only place that signal ever appears. Read it.
  is_job_listing_alert: 'This is an automated digest or alert advertising job openings, rather than correspondence about an application this applicant has made',
};

// A tag fires when its probability clears this. 0.5 is the honest default for a calibrated
// probability and nothing here has been tuned; treat a firing tag as a candidate to read, never as
// a fact. Same discipline as the jevchecker spec: signal, not verdict.
const FIRES_AT = 0.5;

// ⚠ inbox.py hands over some snippets as raw quoted-printable HTML rather than text. Measured on
// the 391-message 30-day jobhunt window, 2026-09-22: 33 snippets (8%) begin with markup and 26 are
// under 40% real words. Worst senders are twinehq.com (28) and myworkday.com. Klook's
// "Application Status Update" was 420 characters of `<!DOCTYPE html>` and `=3D` with no message
// text at all, so is_rejection scored 0.39 and it was missed — off the subject line alone, which
// is the only thing Jev actually had to read.
//
// Cleaning here rather than in postman's decode_snippet, which is the real root cause: that
// function feeds the live outbound mail path and Orion's own digest, and this session is not the
// place to change it. Filed as docs/issues/postman-snippet-html.md.

// What Jev judges. Sender, subject and the cleaned snippet, which is all inbox.py carries per
// message anyway. Not the thread_id or attribution: those are Orion's own derived fields and
// feeding a pipeline's guesses back in as evidence is how a wrong attribution becomes
// self-confirming.
export function stateFor(m) {
  return `From: ${m.from ?? ''}\nDate: ${m.date ?? ''}\nSubject: ${m.subject ?? ''}\n\n${toText(m.snippet)}`;
}

const questions = Object.fromEntries(
  Object.entries(TAGS).map(([id, instructions]) => [id, { type: 'noul', instructions }]));

// A missing answer is recorded as null rather than 0: absent and "definitely not" are different,
// and folding them together would let a partial response read as a clean negative.
export const toTags = (answers) => noulsFrom(answers, Object.keys(TAGS));
export const fired = (tags) => firedTags(tags, FIRES_AT);

async function ask(m, key) {
  const { answers, cost } = await askJev(stateFor(m), questions, key);
  return { tags: toTags(answers), cost };
}

// One call per email, not one call for the whole mailbox. An email is self-contained, and a single
// shared state would let message 7's questions be answered partly from message 3's text — Jev
// evaluates every question against the WHOLE state. Packing is right when chunks need a common
// source (a resume against its basis); it is wrong when they are independent.
const sweep = (messages, key, onDone) => runPool(messages, async (m) => {
  try {
    const { tags, cost } = await ask(m, key);
    return { ...m, tags, cost };
  } catch (e) {
    return { ...m, tags: null, error: e.message };
  }
}, CONCURRENCY, onDone);

function report(rows) {
  const ok = rows.filter((r) => r.tags);
  const failed = rows.filter((r) => r.error);

  for (const r of ok) {
    const f = fired(r.tags);
    const who = String(r.from ?? '').slice(0, 34).padEnd(34);
    const subj = String(r.subject ?? '(no subject)').slice(0, 44).padEnd(44);
    console.log(`${who} ${subj} ${f.length ? f.map(([k, v]) => `${k} ${v}`).join(', ') : '(no tags)'}`);
  }

  // Per-tag counts, which is the point of the exercise: these are now countable.
  console.log('\n  tag                     fires   mean when fired');
  for (const id of Object.keys(TAGS)) {
    const vals = ok.map((r) => r.tags[id]).filter((v) => v !== null);
    const hits = vals.filter((v) => v >= FIRES_AT);
    const mean = hits.length ? hits.reduce((s, v) => s + v, 0) / hits.length : null;
    console.log(`  ${id.padEnd(22)} ${String(hits.length).padStart(5)}   ${mean === null ? '-' : mean.toFixed(2)}`);
  }

  const untagged = ok.filter((r) => fired(r.tags).length === 0).length;
  console.log(`\n  messages        ${ok.length}`);
  console.log(`  no tag fired    ${untagged}`);
  console.log(`  cost            $${ok.reduce((s, r) => s + (r.cost ?? 0), 0).toFixed(5)}`);
  if (failed.length) {
    console.log(`  failed          ${failed.length}`);
    for (const f of failed.slice(0, 5)) console.log(`    ${String(f.subject).slice(0, 50)}: ${f.error}`);
  }
  // A high untagged count is the signal that the vocabulary is wrong, not that the mailbox is
  // quiet. Say so rather than leaving a number to interpret.
  if (ok.length && untagged / ok.length > 0.4) {
    console.log(`\n  ⚠ ${Math.round(untagged / ok.length * 100)}% of messages matched no tag. Either the window is`);
    console.log('    mostly noise, or TAGS is missing a category. Read a few of the untagged ones.');
  }
}

export function selftest() {
  // A missing answer is null, never 0 — otherwise a partial response reads as a clean negative.
  assert.strictEqual(toTags({}).is_rejection, null);
  assert.strictEqual(toTags({ is_rejection: {} }).is_rejection, null);
  assert.strictEqual(toTags({ is_rejection: { noul: 0 } }).is_rejection, 0);
  // Every tag is present in the output even when the answer set is partial, so a consumer can rely
  // on the shape.
  assert.deepStrictEqual(Object.keys(toTags({})), Object.keys(TAGS));
  // Rounding to 2dp, because a noul of 0.8300000000000001 in a report is noise.
  assert.strictEqual(toTags({ needs_reply: { noul: 0.834 } }).needs_reply, 0.83);
  // The threshold is inclusive at the boundary, and a null never fires.
  assert.deepStrictEqual(fired({ a: 0.5, b: 0.49, c: null }).map(([k]) => k), ['a']);
  // Fired tags come back strongest first.
  assert.deepStrictEqual(fired({ a: 0.6, b: 0.9, c: 0.7 }).map(([k]) => k), ['b', 'c', 'a']);
  assert.deepStrictEqual(fired({ a: 0.1 }), []);
  // Quoted-printable, in the order that actually matters: a soft line break decoded after =XX
  // glues the words either side of it together.
  assert.strictEqual(toText('applic=\r\nation'), 'application');
  assert.strictEqual(toText('a=3Db'), 'a=b');
  // Markup goes, and the words inside it survive.
  assert.strictEqual(toText('<p>Thank you for <b>applying</b></p>'), 'Thank you for applying');
  assert.strictEqual(toText('<!DOCTYPE html><html><head><meta charset="utf-8"></head><body>Regret</body></html>'), 'Regret');
  // Script and style bodies are not prose. Stripping tags alone would leave the CSS behind as
  // "content" and it reads like text to a model.
  assert.strictEqual(toText('<style>body{color:red}</style>Hello'), 'Hello');
  assert.strictEqual(toText('<script>var x="apply now"</script>Hi'), 'Hi');
  assert.strictEqual(toText('<!-- hidden -->Visible'), 'Visible');
  // MIME scaffolding is not content. Real shapes from the 2026-09-22 window.
  assert.strictEqual(toText('--91ae4e6db3e694e7bbe369bdae65a8975dab85b2404766f66bf0923ccdf9\nHello'), 'Hello');
  assert.strictEqual(toText('Content-Transfer-Encoding: quoted-printable\nHello'), 'Hello');
  assert.strictEqual(toText('Content-Type: text/plain; charset="utf-8"\nHello'), 'Hello');
  assert.strictEqual(toText('------------------------------=\nHello'), 'Hello');
  // ...but an em-dash-ish run inside a sentence is not scaffolding, and a "Content-Type" mentioned
  // mid-sentence must survive: the patterns are line-anchored for exactly this reason.
  assert.strictEqual(toText('We discussed Content-Type: json in the call'), 'We discussed Content-Type: json in the call');

  // Entities, including the numeric ones Workday emits.
  assert.strictEqual(toText('Tom &amp; Jerry&#39;s'), "Tom & Jerry's");
  assert.strictEqual(toText('a&nbsp;b'), 'a b');
  // An unknown entity becomes a space rather than surviving as literal junk.
  assert.strictEqual(toText('a&zzz;b'), 'a b');
  // Plain text passes through untouched, which is the common case (median ratio was 1.00).
  assert.strictEqual(toText('Thanks for your application.'), 'Thanks for your application.');
  assert.strictEqual(toText(null), '');

  // The state carries the four fields Jev is meant to judge and none of Orion's derived ones.
  const s = stateFor({ from: 'a@b.c', date: 'd', subject: 's', snippet: 'body',
    thread_id: 'LEAK', attribution: 'LEAK' });
  assert.ok(s.includes('a@b.c') && s.includes('s') && s.includes('body'));
  assert.ok(!s.includes('LEAK'), 'derived pipeline fields must not be fed back in as evidence');
  // A message missing every field must still produce a usable state rather than throwing.
  assert.strictEqual(typeof stateFor({}), 'string');
  return 'jevmail selftest OK';
}

const argv = process.argv.slice(2);
const flag = (n) => argv.includes(`--${n}`);
const opt = (n) => { const i = argv.indexOf(`--${n}`); return i < 0 ? null : argv[i + 1]; };

if (flag('selftest')) { console.log(selftest()); process.exit(0); }

const raw = opt('in') ? fs.readFileSync(opt('in'), 'utf8') : fs.readFileSync(0, 'utf8');
const messages = JSON.parse(raw);
if (!Array.isArray(messages)) {
  console.error('expected the JSON array from `inbox.py <identity> --json`');
  process.exit(1);
}

const key = process.env.OPENROUTER_API_KEY;
if (!key) {
  console.error('OPENROUTER_API_KEY is not set. Vault proj/jev; see docs/runbooks/secret-courier.md.');
  process.exit(1);
}

console.log(selftest());
console.log(`sweeping ${messages.length} messages, ${CONCURRENCY} at a time\n`);
let last = 0;
const rows = await sweep(messages, key, (done, total) => {
  if (done - last >= 25 || done === total) { console.error(`  ${done}/${total}`); last = done; }
});
report(rows);
if (opt('json')) {
  fs.writeFileSync(opt('json'), JSON.stringify(rows.map(({ cost, ...r }) => r), null, 2));
  console.log(`\ntags written to ${opt('json')}`);
}
